
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Pichau
 */
public class Janela1 extends javax.swing.JFrame {

    Color  blue;
    public Janela1() {
        this.blue = new Color(0, 0xa9, 0xf5);
        initComponents();
        getContentPane().setBackground(blue);
    }

/**
     * Creates new form Janela1
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox<>();
        btnGroupEstadoCivil = new javax.swing.ButtonGroup();
        btnGroupGenero = new javax.swing.ButtonGroup();
        btnGroupCargo = new javax.swing.ButtonGroup();
        lblNome = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        RdbtnSolteiro = new javax.swing.JRadioButton();
        RdbtnCasado = new javax.swing.JRadioButton();
        RdbtnOutro = new javax.swing.JRadioButton();
        RdbtnMasculino = new javax.swing.JRadioButton();
        RdbtnFeminino = new javax.swing.JRadioButton();
        RdbtnOutro2 = new javax.swing.JRadioButton();
        chkbxCaixa = new javax.swing.JCheckBox();
        chkbxSeguranca = new javax.swing.JCheckBox();
        chkbxAdmnistrativo = new javax.swing.JCheckBox();
        chkbxRepositor = new javax.swing.JCheckBox();
        chkbxAtendente = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblEstadoCivil = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblDeficiencia = new javax.swing.JLabel();
        btnEditarNome = new javax.swing.JButton();
        btnEditarIdade = new javax.swing.JButton();
        btnEditarTelefone = new javax.swing.JButton();
        btnEditarCpf = new javax.swing.JButton();
        btnEditarEmail = new javax.swing.JButton();
        mnCadastrodeCandidato = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNome.setText("Nome ");
        lblNome.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                lblNomeComponentAdded(evt);
            }
        });

        lblIdade.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblIdade.setText("Idade");

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTelefone.setText("Telefone");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEmail.setText("Email");

        lblCpf.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCpf.setText("CPF");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saquarema", "Maricá", "Rio das ostras", "Araruama", "Rio Bonito", "São Pedro", "Iguaba Grande", "Cabo Frio", " " }));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhuma", "Física", "Visual", "Auditiva", "Motora", "Outras" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        btnGroupEstadoCivil.add(RdbtnSolteiro);
        RdbtnSolteiro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RdbtnSolteiro.setText("Solteiro");
        RdbtnSolteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbtnSolteiroActionPerformed(evt);
            }
        });

        btnGroupEstadoCivil.add(RdbtnCasado);
        RdbtnCasado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RdbtnCasado.setText("Casado");

        btnGroupEstadoCivil.add(RdbtnOutro);
        RdbtnOutro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RdbtnOutro.setText("Outro");

        btnGroupGenero.add(RdbtnMasculino);
        RdbtnMasculino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RdbtnMasculino.setText("Masculino");

        btnGroupGenero.add(RdbtnFeminino);
        RdbtnFeminino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RdbtnFeminino.setText("Feminino");

        btnGroupGenero.add(RdbtnOutro2);
        RdbtnOutro2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RdbtnOutro2.setText("Outro");

        btnGroupCargo.add(chkbxCaixa);
        chkbxCaixa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkbxCaixa.setText("Caixa");
        chkbxCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxCaixaActionPerformed(evt);
            }
        });

        btnGroupCargo.add(chkbxSeguranca);
        chkbxSeguranca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkbxSeguranca.setText("Segurança");

        btnGroupCargo.add(chkbxAdmnistrativo);
        chkbxAdmnistrativo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkbxAdmnistrativo.setText("Admnistrativo");
        chkbxAdmnistrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxAdmnistrativoActionPerformed(evt);
            }
        });

        btnGroupCargo.add(chkbxRepositor);
        chkbxRepositor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkbxRepositor.setText("Repositor");

        btnGroupCargo.add(chkbxAtendente);
        chkbxAtendente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkbxAtendente.setText("Atendente");

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/adicionar-ficheiro.png"))); // NOI18N
        jButton1.setText("Adicionar");

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/cesto-de-lixo.png"))); // NOI18N
        jButton2.setText("Excluir");

        lblEstadoCivil.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEstadoCivil.setText("Estado Civíl");

        lblGenero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblGenero.setText("Gênero");

        lblCargo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCargo.setText("Cargo");

        lblCidade.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCidade.setText("Cidade");

        lblDeficiencia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDeficiencia.setText("Deficiência");

        btnEditarNome.setBackground(new java.awt.Color(204, 204, 255));
        btnEditarNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lapis.png"))); // NOI18N
        btnEditarNome.setBorder(null);
        btnEditarNome.setBorderPainted(false);
        btnEditarNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarNomeActionPerformed(evt);
            }
        });

        btnEditarIdade.setBackground(new java.awt.Color(204, 204, 255));
        btnEditarIdade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lapis.png"))); // NOI18N
        btnEditarIdade.setBorder(null);
        btnEditarIdade.setBorderPainted(false);
        btnEditarIdade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnEditarTelefone.setBackground(new java.awt.Color(204, 204, 255));
        btnEditarTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lapis.png"))); // NOI18N
        btnEditarTelefone.setBorder(null);
        btnEditarTelefone.setBorderPainted(false);
        btnEditarTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnEditarCpf.setBackground(new java.awt.Color(204, 204, 255));
        btnEditarCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lapis.png"))); // NOI18N
        btnEditarCpf.setBorder(null);
        btnEditarCpf.setBorderPainted(false);
        btnEditarCpf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnEditarEmail.setBackground(new java.awt.Color(204, 204, 255));
        btnEditarEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lapis.png"))); // NOI18N
        btnEditarEmail.setBorder(null);
        btnEditarEmail.setBorderPainted(false);
        btnEditarEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEmailActionPerformed(evt);
            }
        });

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/usuario32.png"))); // NOI18N
        jMenu3.setText("Cadastro de Candidato");
        mnCadastrodeCandidato.add(jMenu3);

        setJMenuBar(mnCadastrodeCandidato);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(42, 42, 42)
                .addComponent(jButton2)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RdbtnSolteiro)
                            .addComponent(RdbtnOutro)
                            .addComponent(RdbtnCasado)
                            .addComponent(lblEstadoCivil))
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RdbtnOutro2)
                            .addComponent(RdbtnMasculino)
                            .addComponent(RdbtnFeminino)
                            .addComponent(lblGenero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCargo)
                            .addComponent(chkbxAtendente)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkbxAdmnistrativo)
                                    .addComponent(chkbxRepositor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkbxSeguranca)
                                    .addComponent(chkbxCaixa))))
                        .addGap(142, 142, 142))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeficiencia)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCidade))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIdade)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCpf)
                                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(204, 204, 204))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNome)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblIdade)
                                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEditarIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefone)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEditarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEditarEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDeficiencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstadoCivil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RdbtnCasado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RdbtnSolteiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RdbtnOutro))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGenero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RdbtnMasculino)
                                    .addComponent(chkbxAdmnistrativo)
                                    .addComponent(chkbxCaixa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RdbtnFeminino)
                                    .addComponent(chkbxRepositor)
                                    .addComponent(chkbxSeguranca)))
                            .addComponent(lblCargo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RdbtnOutro2)
                            .addComponent(chkbxAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkbxAdmnistrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxAdmnistrativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbxAdmnistrativoActionPerformed

    private void chkbxCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbxCaixaActionPerformed

    private void RdbtnSolteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbtnSolteiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdbtnSolteiroActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void lblNomeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_lblNomeComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNomeComponentAdded

    private void btnEditarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarNomeActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "O campo nome foi limpo");
        txtNome.setText("");
        
        
    }//GEN-LAST:event_btnEditarNomeActionPerformed

    private void btnEditarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RdbtnCasado;
    private javax.swing.JRadioButton RdbtnFeminino;
    private javax.swing.JRadioButton RdbtnMasculino;
    private javax.swing.JRadioButton RdbtnOutro;
    private javax.swing.JRadioButton RdbtnOutro2;
    private javax.swing.JRadioButton RdbtnSolteiro;
    private javax.swing.JButton btnEditarCpf;
    private javax.swing.JButton btnEditarEmail;
    private javax.swing.JButton btnEditarIdade;
    private javax.swing.JButton btnEditarNome;
    private javax.swing.JButton btnEditarTelefone;
    private javax.swing.ButtonGroup btnGroupCargo;
    private javax.swing.ButtonGroup btnGroupEstadoCivil;
    private javax.swing.ButtonGroup btnGroupGenero;
    private javax.swing.JCheckBox chkbxAdmnistrativo;
    private javax.swing.JCheckBox chkbxAtendente;
    private javax.swing.JCheckBox chkbxCaixa;
    private javax.swing.JCheckBox chkbxRepositor;
    private javax.swing.JCheckBox chkbxSeguranca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDeficiencia;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JMenuBar mnCadastrodeCandidato;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
