DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS livros CASCADE;

CREATE TABLE clientes (
	id SERIAL PRIMARY KEY NOT NULL,
	nome VARCHAR(50) UNIQUE NOT NULL,
	endereco VARCHAR(120) NOT NULL,
	logradouro INT NOT NULL
);

CREATE TABLE livros (
	id SERIAL PRIMARY KEY NOT NULL
	
);

SELECT * FROM clientes;